// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Validate environment variables
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error('Missing Supabase environment variables:', {
    url: SUPABASE_URL ? '✓' : '✗',
    key: SUPABASE_PUBLISHABLE_KEY ? '✓' : '✗'
  });
  
  // Provide helpful error message
  if (typeof window !== 'undefined') {
    console.error(
      'Please set the following environment variables:\n' +
      'VITE_SUPABASE_URL\n' +
      'VITE_SUPABASE_PUBLISHABLE_KEY'
    );
  }
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL || 'https://placeholder.supabase.co',
  SUPABASE_PUBLISHABLE_KEY || 'placeholder-key',
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);